import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phunt
 */
public class Ceasar extends javax.swing.JFrame {

    /**
     * Creates new form Ceasar
     */
    public Ceasar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXT_PlaintText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_Key = new javax.swing.JTextField();
        BTN_Encypt = new javax.swing.JButton();
        BTN_GhiFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TXT_Cipher = new javax.swing.JTextField();
        BTN_Dencypt = new javax.swing.JButton();
        BTN_MoFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ceasar");

        jLabel2.setText("PlaintText");

        jLabel3.setText("Khoa");

        BTN_Encypt.setText("v Encypt v");
        BTN_Encypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EncyptActionPerformed(evt);
            }
        });

        BTN_GhiFile.setText("Ghi File");
        BTN_GhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GhiFileActionPerformed(evt);
            }
        });

        jLabel4.setText("Cipher Text");

        TXT_Cipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CipherActionPerformed(evt);
            }
        });

        BTN_Dencypt.setText("^ Dencypt ^");
        BTN_Dencypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DencyptActionPerformed(evt);
            }
        });

        BTN_MoFile.setText("Mở File");
        BTN_MoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MoFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Encypt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(BTN_GhiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(TXT_Key)
                    .addComponent(TXT_PlaintText)
                    .addComponent(TXT_Cipher)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Dencypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_MoFile)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TXT_PlaintText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXT_Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Encypt)
                    .addComponent(BTN_GhiFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_Cipher, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Dencypt)
                    .addComponent(BTN_MoFile))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_EncyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EncyptActionPerformed
        // TODO add your handling code here:
     int k= Integer.valueOf(this.TXT_Key.getText());
     String br= this.TXT_PlaintText.getText();
     this.TXT_Cipher.setText(mahoa(br,k));
    }//GEN-LAST:event_BTN_EncyptActionPerformed

    private void TXT_CipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CipherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_CipherActionPerformed

    private void BTN_GhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GhiFileActionPerformed
        // TODO add your handling code here:
        
        try{
            BufferedWriter bw= null;
            String filename ="D:\\java\\dulieu.txt";
            String s= TXT_Cipher.getText();
            bw=new BufferedWriter(new FileWriter(filename));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null,"đã ghi file thành công!!!"); 
        }catch(IOException ex){
        Logger.getLogger(Ceasar.class.getName()).log(Level.SEVERE,null,ex);
        }
            
    }//GEN-LAST:event_BTN_GhiFileActionPerformed

    private void BTN_DencyptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DencyptActionPerformed
        // TODO add your handling code here:
        int k=Integer.valueOf(this.TXT_Key.getText());
        String br=this.TXT_Cipher.getText();
        this.TXT_PlaintText.setText(mahoa(br,-k));
    }//GEN-LAST:event_BTN_DencyptActionPerformed

    private void BTN_MoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MoFileActionPerformed
        // TODO add your handling code here:
      try{
          BufferedReader br=null;
          String filename="D:\\java\\dulieu.txt";
          br=new BufferedReader(new FileReader(filename));
          StringBuffer sb=new StringBuffer();
          JOptionPane.showMessageDialog(null,"đã mở file thành công!!!");
          
          char[] ca =new char[5];
          while(br.ready()){
              int len = br.read(ca);
              sb.append(ca,0,len);
          }
          br.close();
          System.out.println("du lieu la:"+" "+sb);
          String chuoi=sb.toString();
          TXT_PlaintText.setText(chuoi);
      }catch(IOException ex){
      Logger.getLogger(Ceasar.class.getName()).log(Level.SEVERE,null,ex);
      }

    }//GEN-LAST:event_BTN_MoFileActionPerformed

 char mahoakt(char c,int k)
 {
     if(!Character.isLetter(c)) return c;
     return (char) ((((Character.toUpperCase(c)-'A')+k)%26 + 26)%26 + 'A');
 }
 private String mahoa(String br,int k){
     String kq="";
     int n=br.length();
     for (int i = 0; i < n; i++) 
         kq+=mahoakt(br.charAt(i),k);
     return kq;
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ceasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ceasar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Dencypt;
    private javax.swing.JButton BTN_Encypt;
    private javax.swing.JButton BTN_GhiFile;
    private javax.swing.JButton BTN_MoFile;
    private javax.swing.JTextField TXT_Cipher;
    private javax.swing.JTextField TXT_Key;
    private javax.swing.JTextField TXT_PlaintText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
